language: ruby

cache:
  bundler: true
  directories:
    - reports
    - vendor/cache

rvm:
  - 2.3.5
  - ruby-head

addons:
  apt:
    sources:
      - elasticsearch-5.x
    packages:
      - elasticsearch
      - oracle-java8-set-default

services:
  - elasticsearch
  - memcached

sudo: false

bundler_args: --jobs=3 --retry=3 --without development

git:
  submodules: true

before_install:
  - git submodule update --init
  - sh -c "if [ '$RUBYGEMS_VERSION' != 'latest' ]; then gem update --system $RUBYGEMS_VERSION; fi"
  - gem --version
  - script/install_toxiproxy.sh

before_script:
  - bundle exec rake db:create db:migrate db:test:prepare

script:
  - bundle exec rails test
  - bundle exec rake rubocop
  - script/brakeman
  - bundle exec cap -T > /dev/null

jobs:
  include:
    - stage: docker build
      rvm: 2.3.5
      env:
        - RUBYGEMS_VERSION=2.6.10
      script: docker build -t rubygems/rubygems.org:$TRAVIS_COMMIT .
    - stage: docker push
      rvm: 2.3.5
      env:
        - RUBYGEMS_VERSION=2.6.10
      script: echo docker push quay.io/rubygems/rubygems.org:$TRAVIS_COMMIT

env:
  - RUBYGEMS_VERSION=2.6.10
  - RUBYGEMS_VERSION=latest

matrix:
  allow_failures:
    - env: "RUBYGEMS_VERSION=latest"
    - rvm: ruby-head
  fast_finish: true
